### ISSUE TITLE
How can i run the "bcbio-rnaseq compare" command to compare the bcbio-nextgen output.

### ISSUE THREAD

**Issue by linuxpham** [roryk/bcbio.rnaseq#10]
Hi author,
After run the bcbio-nextgen, I have the final results :

---------------------------------------

2015-07-15_meiyanrnaseq2
Neuron31A_0h-701-2-ATTACT_ATTACT_L002_R1_001
Neuron31A_1h-702-2-TCCGGA_TCCGGA_L002_R1_001
Neuron31A_6h-703-2-CGCTCA_CGCTCA_L002_R1_001
Neuron32B_0h-704-2-GAGATT_GAGATT_L002_R1_001

---------------------------------------

Then , I ran the "bcbio-rnaseq compare" command, I got this error:

--------------------------------------

hoabo@son:~/example/bcbio_nextgen/meiyanrnaseq2/final$ bcbio-rnaseq compare

Usage: bcbio-rnaseq compare [options] project-file key

Options:
  -h, --help
  -n, --cores CORES  1  Number of cores
      --counts-only     Only run count-based analyses
      --seqc            Data is from a SEQC alignment

Arguments:
  project-file    A bcbio-nextgen project file
  key             Key in the metadata field to do pairwise comparisons

--------------------------------------

Thanks !!!

**Comment by roryk** [comment]
Hi @linuxpham,

On your bcbio-nextgen run you probably want to run:

```
bcbio-rnaseq summarize 2015-07-15_meiyanrnaseq2/project-summary.yaml 
```

That will summarize the bcbio-nextgen information in a .Rmd file that you can load into R to start your report. 

Hope that helps!

Best,

Rory

**Comment by linuxpham** [comment]
Hi @roryk,
After run: 

bcbio-rnaseq summarize 2015-07-15_meiyanrnaseq2/project-summary.yaml 

How can i use the output files : qc-summary.Rmd and qc-summary.tmp

I tried to load the R script :
+ source("qc-summary.Rmd")
+ load ("qc-summary.Rmd")
+ Rscript qc-summary.Rmd

but all are the errors.

----------------

Error: object 'html_document' not found
Execution halted

----------------

Please support me.

Thanks !!!

**Comment by linuxpham** [comment]
Hi @roryk ,
I copied the R script in my code.
When ran it, I got this error :

-------------------------

Loading required package: methods

Attaching package: ‘gplots’

The following object is masked from ‘package:stats’:

    lowess

Loading required package: limma
Using  as id variables
Error in tapply(X = X, INDEX = x, FUN = FUN, ...) : 
  arguments must have same length
Calls: reorder -> reorder.factor -> tapply
Execution halted

-------------------------

What is the problem ?

Please help me.

Thanks !!!

**Comment by roryk** [comment]
Hi @linuxpham,

If there is no .html that has been generated, there might be a problem with the qc-summary.Rmd file. You can try to render the HTML in R like this:

If you open up R and do this:

```
library(rmarkdown)
render('qc-summary.Rmd')
```

you should see it make an error where there is a problem. If you could paste in the error that would be awesome. Thanks for the help debugging and sorry for the problems.

**Comment by linuxpham** [comment]
Hi @roryk ,
At the moment, i ignored the HTML documentation.
I note that I can copy the code from 'qc-summary.Rmd' to my code.
When I ran it, I got the error above although I have still get the PDF file such as : http://static.etool.me/v20130815/Rplots.pdf.
What is happen ? Please support me.
Thanks !!

**Comment by roryk** [comment]
Hi @linuxpham,

I'm not sure what the issue is; could you try rendering the HTML file. It will render it in chunks, and then you can see which chunk the error is in which will help us narrow it down. :) Thanks!

**Comment by linuxpham** [comment]
Hi @roryk ,
Wait me some minutes. I will generate the HTML document.
Thanks !!!

**Comment by linuxpham** [comment]
Hi @roryk .
I can not generate the HTML file.
There is an error.

![screen shot 2015-07-16 at 10 24 07 pm](https://cloud.githubusercontent.com/assets/154762/8727355/721d88a8-2c09-11e5-8d61-0988e8596dcc.png)
![screen shot 2015-07-16 at 10 23 59 pm](https://cloud.githubusercontent.com/assets/154762/8727357/7309182c-2c09-11e5-8c1d-8aa850a229d1.png)

Thanks !!!

**Comment by roryk** [comment]
Hi @linuxpham,

Thanks! Hm. Is there any way you could stick up the contents of the project directory somewhere so I could download them and try to see why it isn't working? The directory with the project-summary.yaml file in it. My email address is rory.kirchner@gmail.com if you could email it.

Thanks!

**Comment by linuxpham** [comment]
Hi @roryk ,
I sent the email to you. Please get it.
Thanks !!!

**Comment by roryk** [comment]
Thanks! It seems to work fine for me-- hmm. Here is what it looks like when I run sessionInfo():

```
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pheatmap_1.0.2    CHBUtils_0.1      edgeR_3.8.6       limma_3.22.7     
[5] gplots_2.16.0     reshape_0.8.5     ggplot2_1.0.1     rmarkdown_0.5.3.1

loaded via a namespace (and not attached):
 [1] KernSmooth_2.23-14 MASS_7.3-40        RColorBrewer_1.1-2 Rcpp_0.11.5       
 [5] bitops_1.0-6       caTools_1.17.1     colorspace_1.2-6   compiler_3.1.2    
 [9] digest_0.6.8       evaluate_0.6       formatR_1.1        gdata_2.13.3      
[13] grid_3.1.2         gtable_0.1.2       gtools_3.4.2       htmltools_0.2.6   
[17] knitr_1.9          labeling_0.3       magrittr_1.5       munsell_0.4.2     
[21] plyr_1.8.1         proto_0.3-10       reshape2_1.4.1     scales_0.2.4      
[25] stringi_0.4-1      stringr_1.0.0      tools_3.1.2        yaml_2.1.13 
```

What does it look like if you run that after trying to render the file?

**Comment by linuxpham** [comment]
Hi @roryk ,

It is the output when I run sessionInfo():

![screen shot 2015-07-16 at 11 35 23 pm](https://cloud.githubusercontent.com/assets/154762/8729127/7709a13a-2c13-11e5-86ce-7b4dce1630f6.png)


Thanks !!!

**Comment by lpantano** [comment]
Hi @linuxpham,

if you comment this line: 

`melted$sample = reorder(melted$sample, colnames(counts))`

it runs well??

@roryk, I remember to have some similar problems. Maybe the  `reorder` function changes or something.

**Comment by roryk** [comment]
Hi @linuxpham,

Thanks! I found the problem, I think older versions of the **stats** core library had a different behavior for the reorder function. I dropped using that and it seems to be working fine now. If you re-download the github repository and re-build bcbio-rnaseq, it should work for you now. You'll have to delete the qc-summary.Rmd file and re-run bcbio-rnaseq to get an updated version of the file. Let me know if that doesn't fix it.

**Comment by roryk** [comment]
Yup @lpantano that was totally it, thanks!

**Comment by linuxpham** [comment]
Hi @roryk ,

if I comment this line:

melted$sample = reorder(melted$sample, colnames(counts))

There is an error such as the image below

![screen shot 2015-07-16 at 11 54 38 pm](https://cloud.githubusercontent.com/assets/154762/8729573/20f7b1c6-2c16-11e5-95c6-f24d07d3be21.png)

Thanks !!!

**Comment by roryk** [comment]
Hi @linuxpham,

There is another instance of that line in the boxplot-normalized block, if you comment out that one too it will work I think.

**Comment by linuxpham** [comment]
Hi @roryk ,

At the moment, It is OK.

Thanks for your supporting !!!
