### ISSUE TITLE
Issue : voom_limma_6_vs_7.R can not run successfully

### ISSUE THREAD

**Issue by linuxpham** [roryk/bcbio.rnaseq#13]
Hi @roryk ,

When I run voom_limma_6_vs_7.R :

Rscript 2015-07-15_meiyanrnaseq2/de/voom_limma_6_vs_7.R

I got this error :

![screen shot 2015-07-17 at 12 56 19 am](https://cloud.githubusercontent.com/assets/154762/8731008/aa7d77c0-2c1e-11e5-9317-62645e10d5cd.png)

Thanks !!!

**Comment by roryk** [comment]
Hi @linuxpham,

Sorry about that-- numbers aren't valid names, do you think you could rerun with something more descriptive, like hour7 or day7 so they don't get interpreted as numbers?

**Comment by linuxpham** [comment]
Thanks for you supporting !!!
