### ISSUE TITLE
Can not summarize with FORMULA

### ISSUE THREAD

**Issue by linuxpham** [roryk/bcbio.rnaseq#15]
Hi ,

When i run the command "bcbio-rnaseq summarize project-summary.yaml", it is Ok such as the image below

![screen shot 2015-08-04 at 3 16 42 pm](https://cloud.githubusercontent.com/assets/154762/9056290/4134f6a6-3abc-11e5-8fde-fd4506636f28.png)

When i add the FORMULA ' bcbio-rnaseq summarize project-summary.yaml -f "~ batch" ', it is error such as the invalid parameters

![screen shot 2015-08-04 at 3 15 33 pm](https://cloud.githubusercontent.com/assets/154762/9056284/3c029bf2-3abc-11e5-8587-8f2af45b5d2d.png)

@Notes: I updated the BCBIO-RNASEQ.
Please help me. Thanks !!!

**Comment by lpantano** [comment]
hi,

sorry about that. 
maybe not a solution but worth to try. If you remove the quotes: `-f ~ batch` ? it happens the same?

**Comment by roryk** [comment]
Hi @linuxpham,

The space is the thing killing it; the problem is that the bcbio-rnaseq script is just a bash shell script, and it strips the quotes around the "~ batch". I don't know how to fix this. If you change it so it is just -f ~batch it should work.

**Comment by roryk** [comment]
I removed the spaces in the documentation as well.

**Comment by linuxpham** [comment]
Hi ryrok,
I removed the spaces such as this example: 
-f "~ batch + lane" => -f "~batch+lane"
Now, it run susscessfull.

But, is the result still right (not wrong) ?

Thanks for your suporting.

**Comment by roryk** [comment]
Sorry @linuxpham,

What do you mean by not right? Thanks!

**Comment by linuxpham** [comment]
Hi,

Because i still got this error :

![screen shot 2015-08-04 at 5 59 28 pm](https://cloud.githubusercontent.com/assets/154762/9061714/cf4cdfbe-3ae7-11e5-89a4-bbfa71a1820b.png)

Thanks !!!

**Comment by roryk** [comment]
Hi @linuxpham,

Gotcha-- the summarize command is the one you want to be running to analyze your project. I'll have to poke around a little bit and figure out what is up with the compare functionality.

**Comment by linuxpham** [comment]
Hi @roryk ,

That means : the comparing features do not work correctly now. Is it right ?

OR

Are my commands wrong ?

Please help me. Thanks !!!

**Comment by roryk** [comment]
Hi @linuxpham,

There are a couple of issues:

1) the old issue https://github.com/roryk/bcbio.rnaseq/issues/12 I think is caused by having an old version of DESeq2. Could you update to the newest version and see if that fixes it? That might fix your problems.

2) The compare command is probably not what you want to use. If you just want to analyze your experiment, using the summarize command is what you want to do. 

3) It looks like there is a bug in the compare command. :)

**Comment by linuxpham** [comment]
Hi @ryrok,
I upgraded DESeq2 (newest version). But i still get the old issue #12
Please support me. Thanks!!!

**Comment by roryk** [comment]
Hi @linuxpham,

Sorry for the problems, if you load R and do:

```r
library(DESeq2)
sessionInfo()
```

What version of DESeq2 does it say is installed?

**Comment by linuxpham** [comment]
Hi @roryk ,

the version of DESeq2 is "DESeq2_1.2.10"

![screen shot 2015-08-06 at 10 06 41 am](https://cloud.githubusercontent.com/assets/154762/9102966/00a10a4a-3c23-11e5-9c41-55602dfba860.png)

Thanks !!!

**Comment by roryk** [comment]
Hi @linuxpham,

That is a super old version of DESeq2-- if you do:

```r
source("http://bioconductor.org/biocLite.R")
biocLite() 
```

and upgrade your packages to get a newer version of DESeq2, it should work.

**Comment by linuxpham** [comment]
Hi @roryk ,

After upgrade BIOCLITE, 

Deseq2 is OK, but all others are not success (deseq, voom_lima, edgeR)

![screen shot 2015-08-07 at 5 18 16 pm](https://cloud.githubusercontent.com/assets/154762/9133762/60c7e226-3d28-11e5-98f9-647c8697c951.png)

![screen shot 2015-08-07 at 5 13 41 pm](https://cloud.githubusercontent.com/assets/154762/9133763/60c95fd4-3d28-11e5-97c1-300706079361.png)

Please support me. Thanks !!!

**Comment by roryk** [comment]
Hi @linuxpham,

Are voom and limma installed? It doesn't show up in your sessionInfo(). If you go to the bcbio.rnaseq directory and run: Rscript resources/scripts/install_libraries.R, it should install all the dependencies you need.

**Comment by linuxpham** [comment]
Hi @roryk ,

Voom and Limma, EdgeR and Deseq are installed.

![screen shot 2015-08-07 at 7 16 40 pm](https://cloud.githubusercontent.com/assets/154762/9135559/070d5b74-3d39-11e5-8fae-e0a098c22276.png)

![screen shot 2015-08-07 at 7 16 24 pm](https://cloud.githubusercontent.com/assets/154762/9135558/070a9d44-3d39-11e5-828e-a7f99eea4098.png)

![screen shot 2015-08-07 at 7 15 54 pm](https://cloud.githubusercontent.com/assets/154762/9135560/070deec2-3d39-11e5-85ee-ba5781cb7fda.png)

Please support me. Thanks !!!

**Comment by roryk** [comment]
Hi @linuxpham,

Does your experiment have no replicates?

**Comment by linuxpham** [comment]
Hi @roryk ,

I see the reason.
My experiment have no replicates.

Thanks for your supporting !!!

**Comment by roryk** [comment]
Hi @linuxpham,

Sorry about that, we didn't put any support for no replicates because it is usually a bad plan to run without any and we didn't want to make it seem like we thought the results were legit. Thanks for all of your helpful comments!
