### ISSUE TITLE
deseq2 error

### ISSUE THREAD

**Issue by kspham** [roryk/bcbio.rnaseq#17]
deseq2 gives error: 
Error in results(dds, independentFiltering = TRUE, addMLE = TRUE) :
 unused argument (addMLE = TRUE)

**Comment by roryk** [comment]
Hi @kspham,

Sorry about that-- if you upgrade your version of DESeq2 installed, this error should be fixed.

**Comment by roryk** [comment]
Hi @kspham,

Going to close this for now, the DESeq2 upgrade has worked in some other instances. Let me know if it didn't work for you and I'll help you out, sometimes if the Bioconductor version is super low DESeq2 can't be upgraded to a new-enough version. If that is the case I can help figure out how to do the Bioconductor upgrade too.

**Comment by kspham** [comment]
Thanks Rory for the great work -- it works !

**Comment by roryk** [comment]
Thanks for following up!
