### ISSUE TITLE
trouble running lein run

### ISSUE THREAD

**Issue by scatreux** [roryk/bcbio.rnaseq#18]
Hi,

I followed the quick start guide, and have lein installed.

but when I run:
lein run simulate -s 5 -d /staging/bcbio.rnaseq/sim_test/
i see:
Running templates/deseq2.template.
but i don't see any results generated in the specified output directory.

Also, if the results of a bcbio-nextgen rnaseq are saved under /bcbio/seqc_test/work
how can I run
lein run compare to use that result directory?

Thanks
Severine

**Comment by roryk** [comment]
Hi @scatreux,

Could you post the whole output from:
```bash
lein run simulate -s 5 -d /staging/bcbio.rnaseq/sim_test/
```

That should be working. To run the compare module:

```bash
lein run compare --seqc path-to-your-project.yaml panel
```

should work if you are running the example dataset. There should be a final directory one up from the work directory, so /bcbio/seqc_test/final that has the project-summary.yaml file to point to. Let me know if that doesn't get you going. Thanks!

**Comment by scatreux** [comment]
ok, the lein run simulate works fine now. will study the output files, thanks.

for the lein run compare, this is what I get:
lein run compare --seqc ./seqc_SRR950078_81_100M/final/2015-03-10_seqc/project-summary.yaml panel
No :main namespace specified in project.clj.

as for the key "panel", what if i have a mix of UHRR and HBRR samples in the same project run?
(I ran a bcbio run with 4 samples (2 UHRR and 2 HBRR). should I still enter panel?

Thanks!
Severine

**Comment by scatreux** [comment]
I have this in the project.clj so i'm not sure what to enter instead

  :aot [bcbio.rnaseq.core]
  :main bcbio.rnaseq.core

**Comment by roryk** [comment]
Hi @scatreux,

Sorry for all of the problems and thanks for posting the issues.

In the YAML datafile, how are UHRR and HBRR specified? There should be a something like panel or sample or something that is what they are. It will fit the model to that, so it will fit:

```r
~ panel
```

as the experimental design, and do differential expression of the different classes by panel.

For the second issue, something seems odd. If you run 

```bash
lein run compare --help
```

does it give the same error?

**Comment by scatreux** [comment]
Hi Rory,

Ok, yes, in the YAML file, i have UHRR and HBRR specified as panel, i.e.:
metadata:
    panel: HBRR

Yes, I get the same error when I type lein run compare --help.
lein run compare --help
No :main namespace specified in project.clj.

**Comment by roryk** [comment]
Thanks @scatreux for the followup, it is very helpful to improve things.

Sorry for the troubles; lein run needs to be run in the bcbio.rnaseq directory, maybe that is the issue?

You can also run the bcbio-rnaseq executable from anywhere if you make it. So if in the bcbio.rnaseq directory you do:

```bash
make
```

it will make a file in bin/bcbio-nextgen that you can move anywhere and run.

Sorry about that, the documentation is very unclear. I will update it now.

**Comment by scatreux** [comment]
ok good. thanks.

we followed those directions, and now we have an executable called bcbio-rnaseq
and when I type
bcbio-rnaseq --help
i get:

Usage: bcbio-rnaseq [subcommand]

Subcommands
-----------
  compare: compare DE callers on the results of a bcbio-nextgen run
  simulate: compare DE callers using simulated data
  summarize: summarize the QC data from a bcbio-nextgen run

You can get more information about each subcommand
e.g.: bcbio-rnaseq simulate --help


let me try next step now! thanks

**Comment by roryk** [comment]
Great-- thanks for all of the feedback @scatreux

**Comment by scatreux** [comment]
Hi Rory,
OK, i still have 2 pending issues:

1) Re: the bcbio.rnaseq simulate, 
it runs succesfully, and creates the following results directory:

rw-rw-r--  1 severinec users    6074 Aug 28 11:31 compare-simulated.R
-rw-rw-r--  1 severinec users    1151 Aug 28 11:31 deseq2_group1_vs_group2.R
-rw-rw-r--  1 severinec users 1727613 Aug 28 11:31 deseq_group1_vs_group2.counts
-rw-rw-r--  1 severinec users    1532 Aug 28 11:28 deseq_group1_vs_group2.R
-rw-rw-r--  1 severinec users  812960 Aug 28 11:31 deseq_group1_vs_group2.tsv
-rw-rw-r--  1 severinec users 1734401 Aug 28 11:31 edgeR_group1_vs_group2.counts
-rw-rw-r--  1 severinec users    1739 Aug 28 11:31 edgeR_group1_vs_group2.R
-rw-rw-r--  1 severinec users  902214 Aug 28 11:31 edgeR_group1_vs_group2.tsv
-rw-rw-r--  1 severinec users  471205 Aug 28 11:28 sim.counts
-rw-rw-r--  1 severinec users   79005 Aug 28 11:28 sim.scores
-rw-rw-r--  1 severinec users    2826 Aug 28 11:27 simulate.R
-rw-rw-r--  1 severinec users       1 Aug 28 11:31 voom_limma_group1_vs_group2.counts
-rw-rw-r--  1 severinec users    1380 Aug 28 11:31 voom_limma_group1_vs_group2.R
-rw-rw-r--  1 severinec users  977658 Aug 28 11:31 voom_limma_group1_vs_group2.tsv

but it doesn't look like there is any plot.
when I type:
Rscript compare-simulated.R
i get
Type 'citation("pROC")' for a citation.

Attaching package: \u2018pROC\u2019

The following objects are masked from \u2018package:stats\u2019:

    cov, smooth, var

Loading required package: methods

Attaching package: \u2018reshape\u2019

The following objects are masked from \u2018package:plyr\u2019:

    rename, round_any

Error in file(file, "rt") : cannot open the connection
Calls: lapply -> FUN -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/staging/bcbio.rnaseq/sim_test3/deseq2_group1_vs_group2.tsv': No such file or directory
Execution halted
looks like the program did not create the missing file.


2) Re: the bcbio-rnaseq compare, when i type the command:
bcbio-rnaseq compare --seqc /mnt/vault/edico_s/results/seqc-test/seqc_SRR950078_81_100M/ panel

I get:
Exception in thread "main" java.io.FileNotFoundException: /mnt/vault/edico_s/results/seqc-test/seqc_SRR950078_81_100M (Is a directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at clojure.java.io$fn__8638.invoke(io.clj:233)
	at clojure.java.io$fn__8577$G__8542__8584.invoke(io.clj:73)
	at clojure.java.io$fn__8650.invoke(io.clj:262)
	at clojure.java.io$fn__8577$G__8542__8584.invoke(io.clj:73)
	at clojure.java.io$fn__8612.invoke(io.clj:169)
	at clojure.java.io$fn__8551$G__8546__8558.invoke(io.clj:73)
	at clojure.java.io$reader.doInvoke(io.clj:106)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:161)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$slurp.doInvoke(core.clj:6278)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at bcbio.rnaseq.config$load_yaml.invoke(config.clj:13)
	at bcbio.rnaseq.config$setup_config.invoke(config.clj:17)
	at bcbio.rnaseq.compare$compare_bcbio_run.invoke(compare.clj:87)
	at bcbio.rnaseq.compare$compare_cli.doInvoke(compare.clj:102)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:617)
	at bcbio.rnaseq.core$_main.doInvoke(core.clj:78)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at bcbio.rnaseq.core.main(Unknown Source)

**Comment by scatreux** [comment]
oops. OK, re: issue #2, my command line was wrong.
I corrected it to:

bcbio-rnaseq compare --seqc /mnt/vault/edico_s/results/seqc-test/seqc_SRR950078_81_100M/final/2015-03-10_seqc/project-summary.yaml panel

and now the error is:
Exception in thread "main" clojure.lang.ArityException: Wrong number of args (2) passed to: compare$run-comparisons
	at clojure.lang.AFn.throwArity(AFn.java:437)
	at clojure.lang.AFn.invoke(AFn.java:43)
	at bcbio.rnaseq.compare$compare_bcbio_run.invoke(compare.clj:89)
	at bcbio.rnaseq.compare$compare_cli.doInvoke(compare.clj:102)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:617)
	at bcbio.rnaseq.core$_main.doInvoke(core.clj:78)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at bcbio.rnaseq.core.main(Unknown Source)

**Comment by roryk** [comment]
Thanks Severine, I'm fixing this now, just testing it. Sorry it took so long to get to this, I've been super busy.

**Comment by roryk** [comment]
I think this should be all set now. Thanks!

**Comment by scatreux** [comment]
Thanks Rory!
I will test it and let you know.

S.

**Comment by scatreux** [comment]
Rory

How do i update to the latest bcbio-rnaseq code? 
with bcbio_nextgen, I type bcbio_nextgen.py upgrade -u development,

but i don't know the equivalent command for bcbio-rnaseq.

Thanks
S

**Comment by roryk** [comment]
Hi Severine,

If you go into the bcbio.rnaseq directory and type git pull it will pull in the new changes. Then you can remake the executable with make and it will make an updated version. Sorry that this isn't automated yet.

**Comment by scatreux** [comment]
Hey Rory

Re: upgrading DESeq2, what are the command lines to check on the installed version
and to upgrade it?

Thanks
S.
