### ISSUE TITLE
issue with qPCR_foldchange.R

### ISSUE THREAD

**Issue by scatreux** [roryk/bcbio.rnaseq#19]
Hello

i was able to run successfully:
bcbio-rnaseq compare --seqc project-summary2.yaml panel 

to completion, except for DESeq2, which version it seems i need to upgrade.

This command line created a folder called 'de'.
i can see there is a R script that got copied in this directory (qPCR_foldchange.R) so i tried running it with:
Rscript qPCR_foldchange.R
but I got the following error:

Type 'citation("pROC")' for a citation.

Attaching package: \u2018pROC\u2019

The following objects are masked from \u2018package:stats\u2019:

    cov, smooth, var

Loading required package: methods
Saving 7 x 7 in image
Error in data.frame(PANEL = panel, ROW = rows, COL = cols, base) : 
  arguments imply differing number of rows: 0, 1
Calls: plot_FC ... facet_train_layout.grid -> layout_grid -> data.frame
Execution halted

any idea what the problem is?
Thanks!
Severine

**Comment by roryk** [comment]
Hi @scatreux,

Yeah-- it is looking for the DESeq2 results and failing when it can't find it. Could you upgrade the DESeq2 version to one that has the addMLE option? That should fix the issue.

**Comment by scatreux** [comment]
Hi Rory

I upgraded DESeq2, and ran 2 tests:

1) bcbio-rnaseq compare project-summary2.yaml panel
it completed successfully, including the deSeq2.
From the de folder, I then ran:
Rscript compare.R and saw this on the console:

<<
Loading required package: methods
Warning message:
In log(df$expr + 1) : NaNs produced
null device 
          1 
null device 
          1 
null device 
          1 
>>
It created the following files:
-rw-rw-r--  1 severinec users    3611 Sep 15 14:04 pval_comparison_plot.pdf
-rw-rw-r--  1 severinec users    3611 Sep 15 14:04 logFC_comparison_plot.pdf
-rw-rw-r--  1 severinec users    3611 Sep 15 14:04 log10expr_comparison_plot.pdf
-rw-rw-r--  1 severinec users     216 Sep 15 14:04 jaccard.tsv

but none of the pdf files can be opened.

2) bcbio-rnaseq compare --seqc project-summary2.yaml panel
It also ran successfully, including deSeq2.
From the de folder I then ran:
Rscript qPCR_foldchange.R 

and saw this on the condsole
<<
Type 'citation("pROC")' for a citation.

Attaching package: \u2018pROC\u2019

The following objects are masked from \u2018package:stats\u2019:

    cov, smooth, var

Loading required package: methods
Saving 7 x 7 in image
Error in data.frame(PANEL = panel, ROW = rows, COL = cols, base) : 
  arguments imply differing number of rows: 0, 1
Calls: plot_FC ... facet_train_layout.grid -> layout_grid -> data.frame
Execution halted
>>
but maybe in this case, it's missing the conversion mapping between the qPCR genes
and the SEQC genes (which is raised in issue #20).

Any help would be appreciated! All the DE algorithms are creating their output files
now, so the last step is the post-processing of the results and plotting, and I'm interested
to understand that final step too.

Thanks
Severine

**Comment by scatreux** [comment]
Hi Rory

I'm still stuck with running compare.R and qPCR_foldchange.R for the 2 command lines:
 bcbio-rnaseq compare project-summary2.yaml panel
 bcbio-rnaseq compare -seqc project-summary2.yaml panel

Would really appreciate if you could help solve the issues as I'm very interested to see the plots 
post-processing the results. The output from all DE algorithms are getting generated successfully
now, so it's only a matter of running the post processing functions.. Almost there!
thanks!
Severine

**Comment by roryk** [comment]
Hi Severine,

Sorry for the delays, I reworked a bunch of the pipeline to run much faster so the test case will run more quickly, and I'm waiting for that to be finished. I've also created a smaller subset of the test so it is not so intensive to run.

**Comment by scatreux** [comment]
OK thanks very much Rory. let me know when I can test it.

BTW I'm interested to run these 2 command lines:
bcbio-rnaseq compare project-summary2.yaml panel
bcbio-rnaseq compare --seqc project-summary2.yaml panel

i.e., both with and without --seqc.

S.

**Comment by scatreux** [comment]
Hello Rpry

any update from your side? Thanks!
Severine
