### ISSUE TITLE
question re: qPCR_foldchange.R

### ISSUE THREAD

**Issue by scatreux** [roryk/bcbio.rnaseq#20]
Hi

re: this piece of code in the function resources/comparisons/qPCR_foldchange.template
plot_FC = function(df) {
    df = df[, c("id", "logFC", "algorithm")]
    colnames(df) = c("id", "logFC", "method")
    qpcr_foldchange = foldchange[, c("id", "logFC")]
    df = merge(df, qpcr_foldchange, by="id")
    colnames(df) = c("id", "seq_logFC", "method", "qPCR_logFC")
    p = ggplot(df, aes(seq_logFC, qPCR_logFC)) + geom_point() + facet_grid(. ~ method) +
        xlab(expression(paste(log["2"],  " fold change via RNA-seq"))) +
            ylab(expression(paste(log["2"], " fold change via qPCR")))
    ggsave(filename=FC_file, plot=p)
}

I understand this piece of code plots the measured logFC from RNA-seq, versus the expected logFC obtained from the qPCR reference file.
I'm wondering however how a given gene is mapped between the RNA-seq file (e.g.,
deseq_HBRR_vs_UHRR.tsv) and the qPCR reference file (qpcr_HBRR_vs_UHRR.tidy).
the list of gene is different between both files, so I'm wondering how the mapping works between the 2.
example of genes from qpcr_HBRR_vs_UHRR.tidy
'18S'
    'ABC1'
    'ABCA1'
    'ABCA2'
    'ABCB1'
    'ABCB11'
    'ABCB6'
    'ABCC1'
    'ABCC11'
    'ABCC2'
    'ABCC4'
example of genes from deseq_HBRR_vs_UHRR.tsv
'ENSG00000223972'
    'ENSG00000227232'
    'ENSG00000243485'
    'ENSG00000237613'
    'ENSG00000268020'
    'ENSG00000240361'
    'ENSG00000186092'
    'ENSG00000238009'
    'ENSG00000239945'
    'ENSG00000233750'
    'ENSG00000237683'
    'ENSG00000268903'
    'ENSG00000269981'

Thanks!
Severine

**Comment by roryk** [comment]
Thanks Severine,

Sorry about that, I'll have a fix for this soon-- the snippet to do the conversion was removed during a cleaning.

**Comment by scatreux** [comment]
great! thanks let me know when ready so I can test again.
S

**Comment by scatreux** [comment]
hello!

any update on this? Thanks!
Severine

**Comment by roryk** [comment]
Hi Severine,

So sorry for the delay I'm working on it right now. 

Best,

Rory

**Comment by roryk** [comment]
Hi Severine,

I fixed these issues, but you'll have to wipe out the DE directory and rerun. I dropped support for DESeq because DESeq2 is strictly better so there is no reason to support DESeq anymore. The plot to look at is the pvalue-auc-plot.pdf plot that is generated. I'll do some more work to generate something more useful to look at next, but this should at least get you going.

**Comment by scatreux** [comment]
Yahoo! Many thanks! I'll test it and let you know!
