### ISSUE TITLE
compare only two metadata-to-test-on if the project file have many

### ISSUE THREAD

**Issue by apastore** [roryk/bcbio.rnaseq#24]
Is possible to run the DE for only two levels of a set of metadata-to-test-on?

I have a project file with 5 different metadata-to-test-on (two different set of control and 3 different set of treatment) all in duplicate. I was wondering if is possible to use one control and one treatment at the time for the bcbio_rnaseq compare.

Thanks!

**Comment by roryk** [comment]
Hi @apastore,

It's tough to answer without seeing the metadata for each sample, and what questions you want to ask from the data. Could you paste that in?

**Comment by apastore** [comment]
Sure! thanks. 

I want to compare mutagenized cell (SF3B1-K666N or SF3B1-K700E) to the parental cell (in this case Parent_cell).

but I also want to compare the mutagenized cell (SF3B1-K666N or SF3B1-K700E) to the same cell mutagenized for with a silent mutation  SF3B1-K700K.



[project-summary.yaml.zip](https://github.com/roryk/bcbio.rnaseq/files/153350/project-summary.yaml.zip)

**Comment by roryk** [comment]
Gotcha, you can do that by doing a formula that is just `~phenotype` and then use contrasts to look at the differences that you want. `bcbio.rnaseq` will kind of do that for you, it will look at every combination of phenotype and compare them to each other.

**Comment by apastore** [comment]
Thanks!
I have tried bcbio-rnaseq compare project-summary.yaml ~phenotype

but i get this error and this kind of R file ( I am using  bcbio-rnaseq installed with bcbio )

and class is empty

WARNING: update already refers to: #'clojure.core/update in namespace: incanter.core, being replaced by: #'incanter.core/update
Running templates/deseq2.template.
Running templates/edgeR.template.
Running templates/voom_limma.template.
Exception in thread "main" java.io.FileNotFoundException: /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/Daichi_Inoue/rnaseq/SF3B1/SF3B1/final/2016-02-23_SF3B1/de/deseq2_.tsv (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at clojure.java.io$fn__9189.invoke(io.clj:229)
	at clojure.java.io$fn__9102$G__9095__9109.invoke(io.clj:69)
	at clojure.java.io$fn__9201.invoke(io.clj:258)
	at clojure.java.io$fn__9102$G__9095__9109.invoke(io.clj:69)
	at clojure.java.io$fn__9163.invoke(io.clj:165)
	at clojure.java.io$fn__9115$G__9091__9122.invoke(io.clj:69)
	at clojure.java.io$reader.doInvoke(io.clj:102)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at incanter.io$read_dataset.doInvoke(io.clj:73)
	at clojure.lang.RestFn.invoke(RestFn.java:486)
	at bcbio.rnaseq.ercc$ercc_analysis_QMARK_.invoke(ercc.clj:20)
	at bcbio.rnaseq.compare$compare_callers.invoke(compare.clj:82)
	at bcbio.rnaseq.compare$compare_bcbio_run.invoke(compare.clj:91)
	at bcbio.rnaseq.compare$compare_cli.doInvoke(compare.clj:102)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:630)
	at bcbio.rnaseq.core$_main.doInvoke(core.clj:93)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at bcbio.rnaseq.core.main(Unknown Source)

# edgeR analysis
# Soneson, C. & Delorenzi, M. A comparison of methods for differential expression
# analysis of RNA-seq data. BMC Bioinformatics 14, 91 (2013).

library(edgeR)
library(tools)
count_file = "/cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/Daichi_Inoue/rnaseq/SF3B1/SF3B1/final/2016-02-23_SF3B1/combined.counts"
out_file = "/cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/Daichi_Inoue/rnaseq/SF3B1/SF3B1/final/2016-02-23_SF3B1/de/edgeR_.tsv"
class = factor(c("","","","","","","","",""), levels=c(""))
project = "final"
counts = read.table(count_file, header=TRUE, row.names="id")
normalized_file = paste(strsplit(out_file, file_ext(out_file)[[1]][[1]]), "counts", sep="")
edgeR.dgelist = DGEList(counts = counts, group = class)
edgeR.dgelist = calcNormFactors(edgeR.dgelist, method = "TMM")
edgeR.dgelist = estimateCommonDisp(edgeR.dgelist)
edgeR.dgelist = estimateTagwiseDisp(edgeR.dgelist, trend = "movingave")
edgeR.test = exactTest(edgeR.dgelist)

# this is to get the data into a common format
# id, logCPM, logFC, pval, pdj
comparison = paste(levels(class)[1], "_vs_", levels(class)[2], sep="")
out_table = edgeR.test$table
out_table$id = rownames(out_table)
out_table$padj = p.adjust(out_table$PValue, method = "BH")
out_table$algorithm = "edgeR"
out_table$expr = 2^out_table$logCPM
out_table = out_table[, c("id", "expr", "logFC", "PValue", "padj", "algorithm")]
colnames(out_table) = c("id", "expr", "logFC", "pval", "padj", "algorithm")
out_table$project = project
write.table(out_table, file=out_file, quote=FALSE, row.names=FALSE,
            sep="\t")
write.table(edgeR.dgelist$pseudo.counts, file=normalized_file,
            quote=FALSE, sep="\t")

**Comment by roryk** [comment]
You probably just want to use the summarize subcommand, which will make some QC graphs and do the DESeq2 fits and output contrasts. The compare functionality is pretty deprecated:

```
 bcbio-rnaseq summarize -f ~phenotype path-to-project-summary.yaml
```

**Comment by apastore** [comment]
Thanks! I was sure I was doing something wrong!
Final question… If I run bcbio-rnaseq coming with bcbio I get this 

There was an issue rendering the Rmarkdown file. You may need to install
   the R libraries (see https://github.com/roryk/bcbio.rnaseq) for instructions.
   If you have done that, there may be an issue with the Rmarkdown file.
Summary report can be found here /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/Daichi_Inoue/rnaseq/SF3B1/SF3B1/final/2016-02-23_SF3B1/summary/qc-summary.Rmd

but If I run the manual installed one I get the summary files

**Comment by roryk** [comment]
Sorry about that, the bcbio-rnaseq with bcbio doesn't have the libraries installed, we're still working on solving the R dependency issues. When you're installing manually it is probably picking up the system installed R, not the one that come with bcbio.

**Comment by apastore** [comment]
Thanks!

**Comment by roryk** [comment]
This is fixed in the recent version of the bioconda package. Right now we're having problems doing some of the single-cell dependencies so the bioconda package doesn't work on OSX. https://github.com/bioconda/bioconda-recipes/issues/476 is the underlying issue, once that gets resolved you can install via OSX. If you want to run it on OSX you'll have to follow the instructions on this repo unfortunately.
