### ISSUE TITLE
Sailfish quant.sf path wrong

### ISSUE THREAD

**Issue by apastore** [roryk/bcbio.rnaseq#25]
Hi Roryk,

when I run bcbio-rnaseq summarize it seem to me the path of the quant.sf files is wrong :

sf_files = file.path("..", "..", rownames(summarydata), "sailfish",
                      rownames(summarydata), "quant.sf")

should be in my case 

sf_files = file.path("..", "..", rownames(summarydata), "sailfish", "quant", "quant.sf")

is this correct?
Thanks!

**Comment by roryk** [comment]
Hi Paul,

Yup, you might have an old version of bcbio.rnaseq installed, if you clone the new repo it should work.

```
 sample_dirs = file.path("..", "..", rownames(summarydata))
  salmon_files = file.path(sample_dirs, "salmon", "quant.sf")
  sailfish_files = file.path(sample_dirs, "sailfish", "quant.sf")
  new_sailfish = file.path(sample_dirs, "sailfish", "quant", "quant.sf")
  new_salmon = file.path(sample_dirs, "salmon", "quant", "quant.sf")
```
It searches all of those paths for the quant.sf files now.

**Comment by apastore** [comment]
Thanks! I was installing through bioconda!

**Comment by roryk** [comment]
Hi Paul,

Oh, dang. I haven't updated the bioconda package in a while, sorry about that. Will do it soon.

**Comment by apastore** [comment]
No, really! It was my fault not to check your code first!

**Comment by roryk** [comment]
Thanks, sorry I forgot to close this issue. I updated the bioconda package awhile ago so this should be all set now.
