### ISSUE TITLE
--organism option

### ISSUE THREAD

**Issue by apastore** [roryk/bcbio.rnaseq#27]
Hi Roryk,

Just a question is the --organism still working?
Thanks!
Alessandro

**Comment by roryk** [comment]
Hi Alesssandro,

It should be working, but it won't actually run the comparisons, it just sets up the functions so you can pass DESEq2 result objects to it and get the pathway analysis back. Let me know if it isn't working. It requires a recent version of clusterProfiler to run, you might need to install the development version from here: https://github.com/GuangchuangYu/clusterProfiler
