### ISSUE TITLE
Running bcbio-rnaseq summarize just generate a qc-summary Rmd file and a few tmp files

### ISSUE THREAD

**Issue by hliu2016** [roryk/bcbio.rnaseq#28]
Hi roryk,
I want to run bcbio-rnaseq to generate bcbio-nextgen report and differential expression analysis using DESeq2. My bcbio-nextgen has been successfully finished. When I use the the following command:
` bcbio-rnaseq summarize ../config/seqc.yaml -f "~batch+panel" -d -o human -s`
I got the output as below:

> WARNING: update already refers to: #'clojure.core/update in namespace: incanter.core, being replaced by: #'incanter.core/update
> Running DESeq2.
> Running DEXSeq, this will take a long time.
> Setting up DEXSeq template.
> Setting up Sleuth template.
> Setting up pathway analysis template.
> Summary report can be found here /app/datamart/RNAseq-example/subset-test/final/../config/summary/qc-summary.Rmd

The running lasted only a few second and in the /config/summary/ directory I found only a qc-summary.Rmd file and a few tmp files that looks like R scripts.

How to make bcbio-rnaseq correctly run? Thanks a lot.

**Comment by roryk** [comment]
Hi @hliu2016,

Sorry about that, if you go to the ` /app/datamart/RNAseq-example/subset-test/final/../config/summary/` directory, load R and do `rmarkdown::render('qc-summary.Rmd')`, does it give you a more informative error?

More practically, we have another repository to do a similar type of report here, which we've mostly deprecated this repository in favor of: https://github.com/hbc/bcbioRNASeq
