### ISSUE TITLE
Subsetting bcbioRNASeq for DESeq analysis

### ISSUE THREAD

**Issue by evchambers** [roryk/bcbio.rnaseq#29]
Hello!

I am trying to subset a bcbiornaseq object to include fewer samples and then run deseq to do the differential analysis. I am having problems with (I assume) the DESeqDataSet object not understanding that I have subset the data and still looking for all the samples in the design. Is there a way to get around this? I have included my code and error message below.

If I run this on the whole bcb dataset and not the subset then I have no error message.

bcb <- bcbioRNASeq(
    uploadDir = "final/",
    interestingGroups = c("phenotype"),
    organism = "Homo sapiens"
)
bcb_samples <- colnames(bcb)[c(7:9, 13:15)]
bcb_subset <- bcb[, bcb_samples]
dds <- as(bcb_subset, "DESeqDataSet")
design(dds) <- ~phenotype
dds <- DESeq(dds)

Error in designAndArgChecker(object, betaPrior) : factors in design formula must have samples for each level. this error can arise when subsetting a DESeqDataSet, in which all the samples for one or more levels of a factor in the design were removed. if this was intentional, use droplevels() to remove these levels, e.g.: dds$condition <- droplevels(dds$condition)

**Comment by mjsteinbaugh** [comment]
Hi @evchambers can you post your `sessionInfo()`?

I'll double check our code for this and see if we need to add a `droplevels()` call to the sample metadata inside `colData()` before coercing to a `DESeqDataSet`.

FYI The repo for the `bcbioRNASeq` R package is now here: https://github.com/hbc/bcbioRNASeq

Best,
Mike

**Comment by mjsteinbaugh** [comment]
In the meantime, I think you can fix this in your `DESeqDataSet` object with this:

```r
dds[["phenotype"]] <- droplevels(dds[["phenotype"]])
```

**Comment by evchambers** [comment]
Thankyou! I ran it with your line added and that seems to have fixed it. I'll post to the right repo next time :)

**Comment by roryk** [comment]
Thanks for following up Emily. Sorry for the confusing repos. :(
