### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by kspham** [roryk/bcbio.rnaseq#3]
hi Rory:
>make
...
Including stax-api-1.0.1.jar
Including tigris-0.1.1.jar
Including edn-java-0.4.4.jar
Including xalan-2.6.0.jar
Including xml-apis-ext-1.3.04.jar
Including xml-apis-1.3.04.jar
Created /raid/sonpham/bcbio/bcbio.rnaseq/bcbio.rnaseq-0.1.1a-SNAPSHOT-standalone.jar
cat bin/bcbio-rnaseq.template target/*-standalone.jar > bin/bcbio-rnaseq
cat: target/*-standalone.jar: No such file or directory
make: *** [all] Error 1

**Comment by roryk** [comment]
Feel free to reopen if this is still an issue. Thanks!
