### ISSUE TITLE
no html file found

### ISSUE THREAD

**Issue by kspham** [roryk/bcbio.rnaseq#4]
Hi Rory:
We used : lein run summarize /raid/final/project-summary.yaml -f "~ batch + panel" 
and it says: Summary report can be found here /raid/final/summary/qc-summary.html
but in that founder, I just see 3 files: 
deseq2-de.tmp
qc-summary.Rmd
qc-summary.tmp
>>> Anything wrong?

**Comment by roryk** [comment]
Thanks Son, I updated the documentation to reflect this minimum requirement.
